topic = "future.quoteTopicProcessed_tick"

[src]
brokers = ["10.168.1.2:9092", "10.168.1.3:9092"]
group_id = "test"
auto_offset_reset = "earliest" #latest
enable_auto_commit = true

[dst]
brokers = ["localhost:9092"]
